"""db init

Revision ID: 124cd1f0dde3
Revises: 
Create Date: 2023-04-23 12:50:02.828838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124cd1f0dde3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('User_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Login', sa.String(length=200), nullable=True),
    sa.Column('Password', sa.String(length=200), nullable=True),
    sa.Column('Photo_Src', sa.String(length=200), nullable=True),
    sa.Column('Email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('User_ID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('Login'),
    sa.UniqueConstraint('Photo_Src')
    )
    op.create_table('Lobby',
    sa.Column('Lobby_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Lobby_Name', sa.String(length=200), nullable=True),
    sa.Column('Creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Creator'], ['User.User_ID'], ),
    sa.PrimaryKeyConstraint('Lobby_ID')
    )
    op.create_table('Lobby_User',
    sa.Column('Relashion_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_ID', sa.Integer(), nullable=True),
    sa.Column('Lobby_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Lobby_ID'], ['Lobby.Lobby_ID'], ),
    sa.ForeignKeyConstraint(['User_ID'], ['User.User_ID'], ),
    sa.PrimaryKeyConstraint('Relashion_ID')
    )
    op.create_table('Task',
    sa.Column('Task_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Task_Tittle', sa.String(length=200), nullable=True),
    sa.Column('Task_Deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('Task_Inittime', sa.TIMESTAMP(), nullable=True),
    sa.Column('Task_Status', sa.String(length=200), nullable=True),
    sa.Column('Lobby_ID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Lobby_ID'], ['Lobby.Lobby_ID'], ),
    sa.PrimaryKeyConstraint('Task_ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Task')
    op.drop_table('Lobby_User')
    op.drop_table('Lobby')
    op.drop_table('User')
    # ### end Alembic commands ###
