"""create kanban db

Revision ID: 60e94728d8be
Revises: f229044a900a
Create Date: 2023-04-24 15:06:19.369871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60e94728d8be'
down_revision = 'f229044a900a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lobby',
    sa.Column('lobby_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lobby_name', sa.String(length=200), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('lobby_id')
    )
    op.create_table('lobby_user',
    sa.Column('relashion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lobby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobby.lobby_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('relashion_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_tittle', sa.String(length=200), nullable=True),
    sa.Column('task_deadline', sa.TIMESTAMP(), nullable=True),
    sa.Column('task_inittime', sa.TIMESTAMP(), nullable=True),
    sa.Column('task_status', sa.String(length=200), nullable=True),
    sa.Column('lobby_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lobby_id'], ['lobby.lobby_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('lobby_user')
    op.drop_table('lobby')
    # ### end Alembic commands ###
