"""added actor

Revision ID: 9ac2bd891616
Revises: 60e94728d8be
Create Date: 2023-04-26 21:15:53.816157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ac2bd891616'
down_revision = '60e94728d8be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
